### ISSUE TITLE
boolean values not properly unmarshalled from vault

### ISSUE THREAD

**Issue by warroyo** [enaml-ops/omg-product-bundle#16]
I am seeing an issue where in  the bundle v0.1.12, cloudfoundry plugin the vault-hash-misc property seems to be ignore. I have validated all of my properties in the has however the deploy product command errors out saying that the flags are missing. if I move the options into the vault-hash-ip vault entry it is able to pick up all of the properties just fine.

**Comment by warroyo** [comment]
turns out this was related to the two properties below

````
"uaa-enable-selfservice-links":false,
  "uaa-ldap-enabled":true,
````

if `true` or `false` is not wrapped in quotes the cli will silently ignore the contents of the vault entry. Could this be improved by adding some meaningful errors?

**Comment by zmb3** [comment]
There are a couple of things at play here:

1. You need to think of our vault logic as mapping flags to _strings_ as entered on the command line (instead of thinking of it as pure JSON).  Another way of putting if you're familiar with Go is to say we are unmarshalling to a `map[string]string` and not a `map[string]interface{}`.  It looks like errors from our `UnmarshalFlags` are being ignored instead of passed on.  The underlying error that you should have seen if we were passing it on correctly would have been something like: `json: cannot unmarshal bool into Go value of type string`.  We can definitely do a better job of reporting the error here, and we could also add support for unquoted booleans, but the latter doesn't resolve the bigger issue which is:

2. The vault unmarshal logic basically has the same effect as a command line of the form `--flagName flagValue`.  This doesn't work for bool flags because they have a different form.  For bool flags, they are false by default, and if `--boolFlag` is present they get set to true.  For "boolT" flags, they are true by default, and set to false only if `--boolTFlag=false` is present.  You've uncovered both cases that the vault unmarshaller is currently not capable of handling:
 - `uaa-ldap-enabled`: a bool flag being set to true (instead of the default value of false)
 - `uaa-enable-selfservice-links`: a boolT flag being set to false (instead of default true)


@xchapter7x

**Comment by allomov** [comment]
@zmb3 do you have update on this issue? could you show you draft code for solving this issue?

**Comment by zmb3** [comment]
@allomov I pushed the draft code to a branch on pluginlib: https://github.com/enaml-ops/pluginlib/tree/vault-unmarshal-bools

This would need to be reviewed prior to being merged, and then the product plugins could vendor in the latests changes and add their own tests with bool values.

**Comment by allomov** [comment]
Thank you for showing this. This solution seems to be clear and straightforward. Looks like in this case all products will need to switch to using string variables instead of bool values. How much time do you think it may take?

**Comment by zmb3** [comment]
> Looks like in this case all products will need to switch to using string variables instead of bool values.

Not quite - the solution is to fix the unmarshaller such that bool JSON values are supported.

**Comment by allomov** [comment]
I see. Thank you for clarification.

How long will it take to merge this changes? What do you think?

**Comment by zmb3** [comment]
All set @allomov.  You can put booleans in Vault as strings or as actual (unquoted) JSON booleans now.

The actual fix was made in pluginlib: https://github.com/enaml-ops/pluginlib/commit/c244e6734dd27c48b5d3cf32d8e1d1c9c0f943a7

**Comment by allomov** [comment]
Cool! Thank you.
